---
name: DaphneCI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Linting
        run: cargo clippy
      - name: Building
        run: cargo build --release
      - name: Testing
        run: cargo test
